### PR TITLE
Add support for unique state/shared terraform environments

### PR DESCRIPTION
**Pull request by rdark**
Commit 52dae86 describes functionality in more detail, but basically this PR allows you to make use of the `-state` switch when calling `plan` and `apply`.

As per other PR, this is based on my own master containing previous commits - let me know if you want me to rebase.

### CODE REVIEW

**Comment by rdark** [comment]
Just FYI - this PR is a WIP; will comment when ready for merge

**Comment by rdark** [comment]
PR ready for merge

**Comment by maclennann** [comment]
Thanks for all the PRs, this is all great!

**Comment by maclennann** [comment]
Published all recent PRs as 0.2.0. 

Also, here, have push access to the repo! Thanks for all the stuff you've contributed.

**Pull request merged**
